apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    name: user-deployment
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-pod
      app: user
  template:
    metadata:
      name: user-pod
      labels:
        name: user-pod
        app: user
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000