apiVersion: v2
type: application
version: 0.0.1
name: user-service
appVersion: "1.0"
description: "user-service"
dependencies:
  - name: postgresql
    version: 10.16.2
    repository: https://charts.bitnami.com/bitnami